### ISSUE TITLE
DeprecationWarning in node.js v7.0.0

### ISSUE THREAD

**Issue by dreamorosi** [sindresorhus/public-ip#12]
In Node.js v7.x (which has become the 'current' Node.js branch just a few weeks ago), a DeprecationWarning is shown.

Not a huge problem, but would be nice to get rid off I think. :)

`DeprecationWarning: Using Buffer without "new" will soon stop working. Use "new Buffer()", or preferably "Buffer.from()", "Buffer.allocUnsafe()" or "Buffer.alloc()" instead.`

**Comment by silverwind** [comment]
Comes from https://github.com/mafintosh/dns-packet.

**Comment by silverwind** [comment]
https://github.com/mafintosh/dns-packet/pull/1

**Comment by silverwind** [comment]
Should be solved by reinstalling the module.

**Comment by dreamorosi** [comment]
Yes I can confirm that it's solved
