### ISSUE TITLE
"files" property excludes browser.js

### ISSUE THREAD

**Issue by substack** [sindresorhus/public-ip#14]
https://github.com/sindresorhus/public-ip/blob/master/package.json#L24-L26

It's probably best not to use the "files" property at all.

**Comment by sindresorhus** [comment]
> It's probably best not to use the "files" property at all.

I disagree. I've been using the `files` property on hundreds of modules for years and this is the first time it happened. It can be solved with tooling, see: https://github.com/sindresorhus/np/issues/82
