### ISSUE TITLE
Can the package be published precompiled to ES5?

### ISSUE THREAD

**Issue by andredicioccio** [sindresorhus/public-ip#17]
Hi there,
Am wondering if this can be published pre-compiled as per this issue with create-react-app.
Thanks.

[https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify](url)

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
