### ISSUE TITLE
Getting Invalid character error on IE 11

### ISSUE THREAD

**Issue by AmChaithanya** [sindresorhus/public-ip#18]
Getting invalid character error in IE 11 when executing the below code in angular 4 application.

publicIp.v4().then(ip =>
{            
     console.log("IP: "+ ip);
});  
  
While debugging, its shows error in vendor.bundle.js and the code that causes the error is below. The error comes in line const v6=` 

const v6seg = '[0-9a-fA-F]{1,4}';
const v6 = `
(
(?:${v6seg}:){7}(?:${v6seg}|:)|                                // 1:2:3:4:5:6:7::  1:2:3:4:5:6:7:8
(?:${v6seg}:){6}(?:${v4}|:${v6seg}|:

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
