### ISSUE TITLE
problem in getting ip 

### ISSUE THREAD

**Issue by Jaihind3** [sindresorhus/public-ip#2]
we are not able to get my system own ip. it`s give me server ip on which ip project is running.

**Comment by sindresorhus** [comment]
Please elaborate. Your issue description couldn't be more unclear.

> which ip project is running.

What IP project?

**Comment by Jaihind3** [comment]
i am using your package on local server then its give me my public ip address but when i test on my live server then it`s give me my server ip address on which my project run.
i want that on live server it give my public ip address not my live server ip address.

**Comment by sindresorhus** [comment]
This module returns the IP of the machine that talks to the outside world.

**Comment by pinal-r** [comment]
> we are not able to get my system own ip. it`s give me server ip on which ip project is running.

I am facing this same issue , what solution you applied ?
