### ISSUE TITLE
trying the module in phantomjs context throw Error: Cannot find module 'dgram'

### ISSUE THREAD

**Issue by AdriwanKenoby** [sindresorhus/public-ip#21]
Hi @sindresorhus,

I try to use public-ip module in [phantomas](https://github.com/macbre/phantomas),

my problem is that I always receive this `Error: Cannot find module 'dgram'`, maybe due to that I'am in node project but using phantomjs, maybe I need the browser.js script to be called, but I don't know how to handle this and it is really hard to debug.

I already reported the issue in phantomas project as I don't know if it is due to specific phantomas behaviour. [https://github.com/macbre/phantomas/issues/715](https://github.com/macbre/phantomas/issues/715)

**Comment by sindresorhus** [comment]
This is a Node.js module. It's not for PhantomJS.

**Comment by sindresorhus** [comment]
Also, you shouldn't use PhantomJS. It's deprecated. Use https://github.com/GoogleChrome/puppeteer instead. It's hundred times better.

**Comment by AdriwanKenoby** [comment]
The phantomas project is planned to be refactored with pupetter, codename chromas.
Thank's for your quick reply
