### ISSUE TITLE
Won't minify in create-react-app build

### ISSUE THREAD

**Issue by tonyc10** [sindresorhus/public-ip#22]
This package breaks the optimized production build for create-react-app, with the following message:

```
Failed to minify the code from this file: 

 	./node_modules/public-ip/browser.js:14 

Read more here: http://bit.ly/2tRViJ9

```

Can you publish this package pre-compiled, so that it will minify?

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
