### ISSUE TITLE
dns-socket library that public-ip uses has deprecation warnings, may need to be updated or somehow handled

### ISSUE THREAD

**Issue by anking** [sindresorhus/public-ip#23]
trying to do an IP check without Internet connection:

```
var ipCheck = require('public-ip').v4();
ipCheck.then();
ipCheck.catch(error => {
      log.error("ERROR: IP CHECK TIMEOUT / Unable to define IP address/ abort mission");
    });
```
catch block will not handle the error, but rather comes up with the following warning:
![image](https://user-images.githubusercontent.com/9019734/44008196-9bad5e52-9e6e-11e8-8adf-114939c1f528.png)

**Comment by silverwind** [comment]
You need to chain your catch directly off the `then`, like `ipCheck.then().catch()`, otherwise it will not catch.
