### ISSUE TITLE
Requires node >=8.6?

### ISSUE THREAD

**Issue by caseprince** [sindresorhus/public-ip#29]
Our app is on node 8.2.1, which seems like it should be sufficient, however when I try to install public-ip (using `yarn add`) I get the following error:

`error got@9.6.0: The engine "node" is incompatible with this module. Expected version ">=8.6".`

Looks like the newest version of `got` wants node `>- 8.6: https://github.com/sindresorhus/got/blob/master/package.json.

Suggest locking down your `got` dependency to `"got": "9.4.0",` vs `"got": "^9.4.0",` so you can remain compatible with older versions of node? Might not be a bad idea to lock down all dependency versions? I'm happy to open a PR if you'd like?

**Comment by sindresorhus** [comment]
It's expected that consumers upgrade patch and minor Node.js versions. Node.js 8.2.1 is ancient and you're vulnerable to a bunch of vulnerabilities.
