### ISSUE TITLE
returning a constant ip & ipv6 not returning data showing query time out

### ISSUE THREAD

**Issue by harshitsinghwap** [sindresorhus/public-ip#31]
hello ,
my site is running on a cloud "goorm.io" and they use aws services.
your tool/library not working.  each time its  returning a constant ip (54.180.139.241) 
if you figure out or trace the ip (54.180.139.241) its showing aws ip's
not showing the client ip.
i dont know what is causing the error ? does it require any depedencies ?
if not then i suggest you to fix this error

**Comment by sindresorhus** [comment]
You are not understanding how this module works.

**Comment by harshitsinghwap** [comment]
lol i think you actully dont knw how this works ! or what iam doing wrong
i will be glad if you explain me in short and i have seen someone raised the same issue,
its returning the server ip insted of user ip.
for your refrence iam psoting my code below 
`const publicIp = require('public-ip');
app.get("/",function(req,res){
res.send("<h1>You triggred our server!!</h1>");
	(async () => {
    console.log(await publicIp.v4());
    //=> '46.5.21.123'
 
    console.log(await publicIp.v6());
    //=> 'fe80::200:f8ff:fe21:67cf'
})();`
