### ISSUE TITLE
Add more public IP checks for better resilience

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/public-ip#32]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/public-ip/issues/32)

See https://github.com/sindresorhus/is-online/issues/64. One or two alternative services to be checked in parallel would probably be beneficial for better resilience against outages.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#33 added backup service ipify in case primary service goes down](https://issuehunt.io/r/sindresorhus/public-ip/pull/33)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/public-ip/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
Yes, it could also check https://www.ipify.org/ through https://github.com/sindresorhus/ipify.

Any other good free trustable IP check APIs? Maybe from Google, Cloudflare, etc?

**Comment by adityapatadia** [comment]
ipify seems the best. I will go ahead with it. Another option I saw was https://ip.seeip.org

**Comment by adityapatadia** [comment]
Amazon one is not officially documented so I think we should avoid that one.

**Comment by silverwind** [comment]
@sindresorhus seeing this ipify module, I can't help but think it's very redundant to this module. Maybe deprecate it in favor of this module and include the ipify check here?

**Comment by adityapatadia** [comment]
I am not going to use the node module. I will use GOT to get address from their API.

**Comment by sindresorhus** [comment]
> seeing this ipify module, I can't help but think it's very redundant to this module. Maybe deprecate it in favor of this module and include the ipify check here?

I don't see the point in deprecating it. It can be useful when you don't care about redundancy, or as an easy add when you just want the IP without having to think about how to talk to the API or what HTTP lib to use.

**Comment by adityapatadia** [comment]
Opened #33

**Comment by CauseOfDev** [comment]
Any update on this? Is the PR going to be merged or is it blocked for some reason?
