### ISSUE TITLE
Bug: Couldn't find your IP

### ISSUE THREAD

**Issue by kristoff2016** [sindresorhus/public-ip#38]
Hi, 
I have no idea when I connected to router it can not get response from router check IP4 if I used 3G or 4G it is working fine. I have no idea why it is just said `Couldn't find your IP` but when I check my IP address it could see as well  reference: https://whatismyipaddress.com/

Thank you

**Comment by lessfish** [comment]
we are in the same boat, @sindresorhus do you have time to check it over?

**Comment by sindresorhus** [comment]
Try v4: https://github.com/sindresorhus/public-ip/releases/tag/v4.0.0 It has better fallbacks and should be more reliable. Let me know if it solves your problem.

**Comment by kristoff2016** [comment]
thank you will try it and let you know soon

**Comment by kristoff2016** [comment]
this was fixed! thank you
