### ISSUE TITLE
Not working with PrivateInternetAccess VPN

### ISSUE THREAD

**Issue by MaffooBristol** [sindresorhus/public-ip#41]
Hi,

For some reason it appears that this module times out when I change my location via the PIA VPN.

Hitting https://checkip.amazonaws.com/ directly in my browser is fine however for showing the remote IP.

Just as a note the https://www.npmjs.com/package/external-ip package works with the same VPN, although I don't like having to promisify it so would prefer this module.

Any ideas as to why this could be?

Thanks
Matt

**Comment by sindresorhus** [comment]
Does setting the `onlyHttps` option to `true` change anything?

**Comment by MaffooBristol** [comment]
... yes 😄

**Comment by aguyinmontreal** [comment]
This issue is still not fixed! Will try the suggested workaround.

**Comment by aguyinmontreal** [comment]
suggested work around not working
