### ISSUE TITLE
Support for zscaler

### ISSUE THREAD

**Issue by jgroom33** [sindresorhus/public-ip#44]
some organizations use zscaler.  This causes some ip resolver services to recognize the zscaler IP instead of the actual user's IP.

This issues is to request the support of overriding the standard ip address resolvers (icanhazip and ipify) with a list of user defined resolvers.

**Comment by sindresorhus** [comment]
Just curious, what resolvers would you use instead?

**Comment by jgroom33** [comment]
Strangely, the ipify resolver returns the correct IP. But the icanhazip returns the zscaler ip.

So, for now it seems that reversing the order of the array would `resolve` the issue.

**Comment by sindresorhus** [comment]
The Ipify service is open source, so I think it would be worth opening an issue over there to support Zscaler: https://github.com/rdegges/ipify-api

**Comment by jgroom33** [comment]
Ipify operates as desired.

The first item (icanhazip) in the lookup array does not. Opening an issue on that repo could be appropriate.

**Comment by sindresorhus** [comment]
Right. I guess we could change the order.

**Comment by jgroom33** [comment]
I think as a workaround, I'll probably just do a fetch to the URL directly.
I don't understand the behavior of zscaler enough to believe that switching the order is a permanent fix.
