### ISSUE TITLE
Will it detect bots?

### ISSUE THREAD

**Issue by Theeeus** [sindresorhus/public-ip#48]
I'm trying to whitelist the bots of a certain ad network. However, their IPs don't seem to be getting detected.

So my question is: Will bots normally get detected? Is there a way to test?

**Comment by sindresorhus** [comment]
The description of this package is:

> Get **your** public IP address

How is this related to getting **your** IP address?

**Comment by Theeeus** [comment]
> The description of this package is:
> 
> > Get **your** public IP address
> 
> How is this related to getting **your** IP address?

Well, it works for getting users IP addresses, so my question is if it will work if these users are actually bots.

**Comment by Richienb** [comment]
The code will never check if the user is a bot so it will always work
