### ISSUE TITLE
VPN issue #41 still not fixed, workaround not working

### ISSUE THREAD

**Issue by aguyinmontreal** [sindresorhus/public-ip#49]
> Error: Couldn't find your IP
>     at promise (C:\Users\Emilio\WebstormProjects\iplogger\node_modules\public-ip\index.js:172:10)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> 

If you need credentials to see what is going on, I can share mine with you if promise not to share them further.

_Originally posted by @aguyinmontreal in https://github.com/sindresorhus/public-ip/issues/41#issuecomment-665117966_

**Comment by sindresorhus** [comment]
There's not enough information here to do anything about it. Most of these issues are caused by you trying to get an IPv6 address and only a IPv4 one being available or the other way around. https://github.com/sindresorhus/public-ip/issues/45 will solve that problem.
