### ISSUE TITLE
Making this library lighter?

### ISSUE THREAD

**Issue by ZitRos** [sindresorhus/public-ip#54]
Hello!

I appreciate all the work done, including this library. The `got` package is also amazing itself.

However, I ask myself does this `puclic-ip` library really deserves 2 MB of additional dependencies just to make a few (parallel) HTTP requests?

```
$ npm init
$ npm install got
...
+ got@11.8.0
added 30 packages
...
$ du -sh node_modules/
2.0M    node_modules/
```

What do you think of making it depend only on the standard `https` library? Refactoring seems to be just around 10-30 more LOC in terms of this tiny library.

**Comment by sindresorhus** [comment]
> Refactoring seems to be just around 10-30 more LOC in terms of this tiny library.

I was this naive too when I first made Got. Initially Got was just a 50 line wrapper around `https`. How wrong was I. `https` is pretty much unusable in real-world situations. Networking is complex and awful and Got is big because of this reality. I will consider switching to `window.Fetch` when Node.js eventually gets built-in support for it. Until then, I'd rather have a large size and reliability than not.

**Comment by ZitRos** [comment]
@sindresorhus absolutely correct explanation for `got` as a http(s) requests library, thank you!

> I will consider switching to window.Fetch when Node.js eventually gets built-in support for it

So for now, let's maybe then replace `got` with `node-fetch`? 😏 I know it sounds like replacing your work with someone else's, but `node-fetch` is just 160kb unpacked and **0 dependencies**. Also, some people [even suggest](https://github.com/nodejs/node/issues/19393) to bring its implementation into the code.

What do you think?

**Comment by sindresorhus** [comment]
I'm not interested in switching at this point. Switching comes with a risk, and for me, no reward. Also, from experience, `node-fetch` is quite buggy (I use it in my https://github.com/sindresorhus/ky-universal project). I use Got in a lot of projects and it deduplicates better than `node-fetch` would.

**Comment by ZitRos** [comment]
Thanks for explaining. Now I can see both sides.
