### ISSUE TITLE
(Error): Couldn't find your IP

### ISSUE THREAD

**Issue by haris-crewlogix** [sindresorhus/public-ip#56]
I am getting this error.

Unhandled Rejection (Error): Couldn't find your IP

const ip6 = await publicIp.v6();

Can you please have a look and let me know the solution. Thanks.

**Comment by ErikGaston** [comment]
I have the same problem

**Comment by haris-crewlogix** [comment]
@ErikGaston Use Ip4, I think it happens sometimes the client (User) does not have the ip6 assigned which causes this error.

**Comment by haris-crewlogix** [comment]
@tainefreitas Hi, that is weird, its working fine on my side. the IP4.

**Comment by sindresorhus** [comment]
There's not enough information here to do anything about it. Most of these issues are caused by you trying to get an IPv6 address and only a IPv4 one being available or the other way around. https://github.com/sindresorhus/public-ip/issues/45 will solve that problem.
