### ISSUE TITLE
Error while trying to retrieve IPv4

### ISSUE THREAD

**Issue by jodinathan** [sindresorhus/public-ip#6]
[TypeError: Cannot assign to read only property '_ttl_expires' of true] stack: 
  - TypeError: Cannot assign to read only property '_ttl_expires' of true
  -     at MemoryStoreExpire.set (/Applications/XAMPP/xamppfiles/htdocs/socketmw/node_modules/public-ip/node_modules/native-dns/node_modules/native-dns-cache/cache.js:77:27)
  -     at /Applications/XAMPP/xamppfiles/htdocs/socketmw/node_modules/public-ip/node_modules/native-dns/lib/platform.js:271:25
  -     at Array.forEach (native)
  -     at /Applications/XAMPP/xamppfiles/htdocs/socketmw/node_modules/public-ip/node_modules/native-dns/lib/platform.js:270:26
  -     at fs.js:336:14
  -     at FSReqWrap.oncomplete (fs.js:99:15)
message: Cannot assign to read only property '_ttl_expires' of true """

**Comment by sindresorhus** [comment]
The error is coming from https://github.com/tjfontaine/node-dns, so I would open an issue over there. Make sure to include Node.js and OS version.
