### ISSUE TITLE
ESM packages (public-ip) need to be imported. Use 'import' to reference the package instead.

### ISSUE THREAD

**Issue by VishwaGauravIn** [sindresorhus/public-ip#60]
![image](https://user-images.githubusercontent.com/81325730/152016749-d21045af-ef02-4367-b9c1-961555989150.png)

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by noamsan** [comment]
I am also experiencing this issue. I realize there is no call to `require()` in the library.

According to [this SO question](https://stackoverflow.com/questions/70009543/require-of-es-modules-not-supported), it may be related to the fact that [`package.json`](https://github.com/sindresorhus/public-ip/blob/7c155f27aef62a602f24605d6eb4e3772e1ec0f9/package.json#L13) specifies `"type": "module"`.
