### ISSUE TITLE
Unable to handle exception for CancelError

### ISSUE THREAD

**Issue by doutatsu** [sindresorhus/public-ip#69]
I've been trying to figure out why I am getting an uncaught exception, even though I specifically catch the error originating from public-ip:

```
browser.js:53 Uncaught (in promise) CancelError: Request was cancelled
    at browser.js:53:11
    at new Promise (<anonymous>)
    at sendXhr (browser.js:36:18)
    at browser.js:79:15
    at queryHttps (browser.js:93:2)
    at publicIpv4 (browser.js:105:9)
    at publicIp2 (core.js:13:23)
    at headers (sessions.js?t=1691585655153:8:22)
    at create (sessions.js?t=1691585655153:17:45)
    at Proxy.submitForm (TheSignIn.vue:80:32)
```

```js
const headers = async () => {
  try {
    const ip = await publicIp();
    return { 'X-Forwarded-For': ip };
  } catch (error) {
    return { 'X-Forwarded-For': null };
  }
};
```

**Comment by doutatsu** [comment]
@sindresorhus 6.0.1

**Comment by doutatsu** [comment]
Is it as simple as removing this cancel in the ip6 lookup? I suppose I can also just for now switch to looking up ip4 only, instead of the combined method

**Comment by AliceCengal** [comment]
But why isn't the catch catching the Error? Right now it doesn't seem to be possible to handle the Error gracefully at all, Promise.catch and try/catch both fails to handle the CancelError.

**Comment by clibu** [comment]
I've just updated to v6.01 and spent the last 2 hours trying to catch ``CancelError`` and finally found this issue. I've dropped back to use ``publicIpv4()`` which is fine for now. Looking forward to a fix though.
