### ISSUE TITLE
Update aggregate-error dependency to latest version

### ISSUE THREAD

**Issue by 117503445** [sindresorhus/public-ip#72]
As <https://github.com/sindresorhus/aggregate-error/issues/22> mentions, the old version of aggregate-error 4.0.1 references the old version of clean-stack 4.2.0. clean-stack 4.2.0 warns about `Module "os" has been externalized for browser compatibility. clean-stack 4.2.0 on vite warns `Module "os" has been externalized for browser compatibility. cannot access "os.homedir" in client code.

This has been fixed in the new version of clean-stack. Then via [<https://github.com/sindresorhus/aggregate-error/commit/6e107f6b4d20ee57d6f1b8a33700fd5290c5936b#diff- 5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15>](https://github.com/sindresorhus/aggregate-error/commit/6e107f6b4d20ee57d6f1b8a33700fd5290c5936b) , the new version of aggregate-error upgrades the dependencies and fixes this issue as well.

What this project needs to do is upgrade aggregate-error to 5.0.0.

**Comment by sindresorhus** [comment]
The dependency has been removed in the latest version
