### ISSUE TITLE
-4 and -6 as CLI args?

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/public-ip#9]
I think this is pretty standard among CLI tools, and enables one to force v4. Thoughts?

**Comment by sindresorhus** [comment]
What CLI tools? I've never seen that before. There's already a `--ipv6`. Why would you need both? Just curious :)

**Comment by silverwind** [comment]
curl:
````
 -4, --ipv4          Resolve name to IPv4 address
 -6, --ipv6          Resolve name to IPv6 address
````
nc:
````
usage: nc [-46CDdhklnrtUuvz]
````
wget:
````
  -4,  --inet4-only                connect only to IPv4 addresses
  -6,  --inet6-only                connect only to IPv6 addresses
````
Some tools do seperate binaries like `ping` and `ping6`, but overall the scheme is pretty consistent. Having `-4` is nice when you're on a dual stack host that has both a v4 and a v6 address. I think we could opt to use args like curl has above, to keep compatibilty.

**Comment by sindresorhus** [comment]
:+1: Alright. Sounds good.

**Comment by silverwind** [comment]
Okay, I'll get to it.
